#!/bin/bash
_hpm() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="install makepkg remove source-install local-install clean update \
            upgrade list-installed"

    case "${prev}" in
        hpm)
            if [[ ${cur} == * ]] ; then
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            fi
            ;;
        install)
            local rpackages="$(cat /etc/hpm/pkdb/complist | xargs echo)"
            COMPREPLY=( $(compgen -W "${rpackages}" -- ${cur}) )
            return 0
            ;;
        local-install)
            local packages=$(for x in `ls . | grep hpac`; do echo $x; done)
            COMPREPLY=( $(compgen -W "${packages}" -- ${cur}) )
            return 0
            ;;
        source-install)
            local args=$(for x in `ls .`; do echo $x; done)
            COMPREPLY=( $(compgen -W "${args}" -- ${cur}) )
            return 0
            ;;
        makepkg)
            local args=$(for x in `ls .`; do echo $x; done)
            COMPREPLY=( $(compgen -W "${args}" -- ${cur}) )
            return 0
            ;;
        *)
        ;;
    esac
}
complete -F _hpm hpm
